pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r * public/
    - ls -la public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
