pages:
  stage: deploy
  script:
    - apt-get update && apt-get install -y rsync
    - mkdir -p public
    - rsync -av --exclude=public . public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
